### PR TITLE
Use fiducial cut in local coord

### PR DESCRIPTION
**Pull request by cgalloni**
Things seems to be working, but since it is a large change please review. 

Also if it doesn't work right away, let me know.

Maybe the input parameters  rangePropPhi_Err , rangePropR_Err should be change as well, but I wasn't sure how to change them, so I left them untouched.

### CODE REVIEW

**Comment by lpetre-ulb** [comment]
You may want to delete the `extract_boundaries.py` script as well since it is no longer useful. :wink:

**Comment by cgalloni** [comment]
might it become handy at any point, as an example of how to loop on ntuple to extract info?

**Comment by lpetre-ulb** [comment]
That's why the history of Git exists.

**Comment by cgalloni** [comment]
I'll forget it ever existed..
but ok

**Comment by cgalloni** [comment]
but alright, removed

**Comment by fraivone** [comment]
The PR fixes a long standing issue. 
In the past the fiducial cuts  were applied based on global R,phi coordinates. Making sure that the hits were at farther away from the chamber boundaries. 

That caused the boundaries to be shaped as a truncated ring rather than trapezoidal:
image


Even worse, due to the alignment each chamber had their own boundaries. 
Not to mention that the math was simply wrong (the boundaries `Rmin` and `RMax` were not measured from the center as the author of the code thought :D ) causing the fiducial cuts to go wild:
image


The new method is based on Local boundaries cuts and improves:
* Fiducial cuts can now be trapezoidal, being based on Loc_Y and Loc_strip
* Fiducial boundaries only depend on the chamber shape type (Long, Short, GE21) and not on each chamber individually, since the alignment corrections are only applied when transforming local coordinates to global. 
* Dropping the boundaries in global R and phi simplifies the code. Some ugly tricks have now been removed

## Resulting plots
(no cuts fiducial cut on the strip is shown)
### GE11 Long
image

### GE11 Short
image

### GE21 
image

**Pull request merged**
